//! The ticket: the unit of work, and the message a worker is assigned.
//!
//! A ticket pins down *what done means*, the files it owns, and its budget —
//! never *how* (handoff §6). `assignment_message` renders it into exactly the
//! user message a human would have typed, plus the report contract the worker
//! must honor to end its turn.

use crate::report::REPORT_FENCE;
use serde::{Deserialize, Serialize};

/// Per-ticket resource ceiling. The server kills and escalates on breach
/// (handoff §9). Phase 1 enforces wall-clock; the token cap is carried but not
/// yet enforced mid-turn.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct Budget {
    pub wall_secs: u64,
    #[serde(default)]
    pub max_tokens: Option<u64>,
}

impl Default for Budget {
    fn default() -> Self {
        Self { wall_secs: 300, max_tokens: None }
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct Ticket {
    /// External id, e.g. `T-041`. Never generated by the fleet.
    pub id: String,
    pub title: String,
    /// Description + acceptance criteria: the substance of the work.
    pub body: String,
    /// Paths this ticket may write. Enforced by the PreToolUse guard (Phase 2+);
    /// declared here from day one so the contract is stable.
    #[serde(default)]
    pub files_owned: Vec<String>,
    /// Worker slot currently assigned, if any.
    #[serde(default)]
    pub slot: Option<u8>,
    #[serde(default)]
    pub state: crate::event::TicketState,
    #[serde(default)]
    pub budget: Budget,
}

impl Ticket {
    pub fn new(id: impl Into<String>, title: impl Into<String>, body: impl Into<String>) -> Self {
        Self {
            id: id.into(),
            title: title.into(),
            body: body.into(),
            files_owned: Vec::new(),
            slot: None,
            state: crate::event::TicketState::Backlog,
            budget: Budget::default(),
        }
    }

    pub fn with_files(mut self, files: Vec<String>) -> Self {
        self.files_owned = files;
        self
    }

    pub fn with_budget(mut self, budget: Budget) -> Self {
        self.budget = budget;
        self
    }

    /// The exact text written to the worker's stdin to start its turn. It reads
    /// like a message a human would type, and closes with the report contract —
    /// the one instructional guardrail Phase 1 relies on (handoff §9).
    pub fn assignment_message(&self) -> String {
        let files = if self.files_owned.is_empty() {
            "(none declared — ask if unsure what you may touch)".to_string()
        } else {
            self.files_owned.join(", ")
        };
        format!(
            "Ticket {id}: {title}\n\n\
             {body}\n\n\
             Files you own (write only these): {files}\n\n\
             When you are finished, end your final message with a single fenced \
             code block tagged `{fence}` containing a JSON object with these keys: \
             ticket, status (one of done|blocked|needs-decision|failed), summary \
             (≤200 words), branch, diffstat, decisions (array), questions (array), \
             risks (array), followups (array). Example:\n\n\
             ```{fence}\n\
             {{\"ticket\":\"{id}\",\"status\":\"done\",\"summary\":\"...\",\
             \"decisions\":[],\"questions\":[],\"risks\":[],\"followups\":[]}}\n\
             ```",
            id = self.id,
            title = self.title,
            body = self.body,
            files = files,
            fence = REPORT_FENCE,
        )
    }

    /// The reprompt sent when a turn ends with no report block (handoff §5).
    pub const NO_REPORT_REPROMPT: &'static str =
        "You ended your turn without filing a report. File one now: end your \
         message with the fenced `fleet-report` JSON block described earlier.";
}
